### ISSUE TITLE
Errors when trying to complile

### ISSUE THREAD

**Issue by DrNebin** [OttoDIY/OttoDIYLib#10]
I am on OS X. I installed all the libraries as instructed. I am able to use the blockly website to create code, paste it into the Arduino IDE and upload and run the code. However, we have OttoDIYPlus and my kids want to use the bluetooth app (there is no Blockly version of the bluetooth code that I can see). I tried opening the DIYplus BT INO file V9 and V10, but even with the libraries installed I get many error messages related to the libraries, specifically regarding serial communication. I am pasting them below. Please give guidance.

`Arduino: 1.8.13 (Mac OS X), Board: "Arduino Nano, ATmega328P (Old Bootloader)"

OttoPLUS_APP_V10:25:1: error: 'SoftwareSerial' does not name a type; did you mean 'HardwareSerial'?
 SoftwareSerial BTserial = SoftwareSerial(11,12); //  TX  RX of the Bluetooth
 ^~~~~~~~~~~~~~
 HardwareSerial
OttoPLUS_APP_V10:26:20: error: 'BTserial' was not declared in this scope
 SerialCommand SCmd(BTserial);  //The SerialCommand object
                    ^~~~~~~~
/Users/devinnamaky/Downloads/otto-diy-plus/Codes/OttoPLUS_APP_V10/OttoPLUS_APP_V10.ino:26:20: note: suggested alternative: 'Serial'
 SerialCommand SCmd(BTserial);  //The SerialCommand object
                    ^~~~~~~~
                    Serial
/Users/devinnamaky/Downloads/otto-diy-plus/Codes/OttoPLUS_APP_V10/OttoPLUS_APP_V10.ino: In function 'void setup()':
OttoPLUS_APP_V10:94:3: error: 'BTserial' was not declared in this scope
   BTserial.begin(9600);
   ^~~~~~~~
/Users/devinnamaky/Downloads/otto-diy-plus/Codes/OttoPLUS_APP_V10/OttoPLUS_APP_V10.ino:94:3: note: suggested alternative: 'Serial'
   BTserial.begin(9600);
   ^~~~~~~~
   Serial
OttoPLUS_APP_V10:123:8: error: 'class SerialCommand' has no member named 'addDefaultHandler'; did you mean 'setDefaultHandler'?
   SCmd.addDefaultHandler(receiveStop);
        ^~~~~~~~~~~~~~~~~
        setDefaultHandler
/Users/devinnamaky/Downloads/otto-diy-plus/Codes/OttoPLUS_APP_V10/OttoPLUS_APP_V10.ino: In function 'void move(int)':
OttoPLUS_APP_V10:434:3: error: 'BTserial' was not declared in this scope
   BTserial.println("M:END");
   ^~~~~~~~
/Users/devinnamaky/Downloads/otto-diy-plus/Codes/OttoPLUS_APP_V10/OttoPLUS_APP_V10.ino:434:3: note: suggested alternative: 'Serial'
   BTserial.println("M:END");
   ^~~~~~~~
   Serial
/Users/devinnamaky/Downloads/otto-diy-plus/Codes/OttoPLUS_APP_V10/OttoPLUS_APP_V10.ino: In function 'void receiveGesture()':
OttoPLUS_APP_V10:495:3: error: 'BTserial' was not declared in this scope
   BTserial.println("H:END");
   ^~~~~~~~
/Users/devinnamaky/Downloads/otto-diy-plus/Codes/OttoPLUS_APP_V10/OttoPLUS_APP_V10.ino:495:3: note: suggested alternative: 'Serial'
   BTserial.println("H:END");
   ^~~~~~~~
   Serial
/Users/devinnamaky/Downloads/otto-diy-plus/Codes/OttoPLUS_APP_V10/OttoPLUS_APP_V10.ino: In function 'void receiveName()':
OttoPLUS_APP_V10:687:5: error: 'BTserial' was not declared in this scope
     BTserial.write("AT+NAMEOTTODIA");
     ^~~~~~~~
/Users/devinnamaky/Downloads/otto-diy-plus/Codes/OttoPLUS_APP_V10/OttoPLUS_APP_V10.ino:687:5: note: suggested alternative: 'Serial'
     BTserial.write("AT+NAMEOTTODIA");
     ^~~~~~~~
     Serial
/Users/devinnamaky/Downloads/otto-diy-plus/Codes/OttoPLUS_APP_V10/OttoPLUS_APP_V10.ino: In function 'void requestName()':
OttoPLUS_APP_V10:710:3: error: 'BTserial' was not declared in this scope
   BTserial.print("E:");
   ^~~~~~~~
/Users/devinnamaky/Downloads/otto-diy-plus/Codes/OttoPLUS_APP_V10/OttoPLUS_APP_V10.ino:710:3: note: suggested alternative: 'Serial'
   BTserial.print("E:");
   ^~~~~~~~
   Serial
/Users/devinnamaky/Downloads/otto-diy-plus/Codes/OttoPLUS_APP_V10/OttoPLUS_APP_V10.ino: In function 'void requestDistance()':
OttoPLUS_APP_V10:723:3: error: 'BTserial' was not declared in this scope
   BTserial.print("D:");
   ^~~~~~~~
/Users/devinnamaky/Downloads/otto-diy-plus/Codes/OttoPLUS_APP_V10/OttoPLUS_APP_V10.ino:723:3: note: suggested alternative: 'Serial'
   BTserial.print("D:");
   ^~~~~~~~
   Serial
/Users/devinnamaky/Downloads/otto-diy-plus/Codes/OttoPLUS_APP_V10/OttoPLUS_APP_V10.ino: In function 'void requestNoise()':
OttoPLUS_APP_V10:736:3: error: 'BTserial' was not declared in this scope
   BTserial.print("N:");
   ^~~~~~~~
/Users/devinnamaky/Downloads/otto-diy-plus/Codes/OttoPLUS_APP_V10/OttoPLUS_APP_V10.ino:736:3: note: suggested alternative: 'Serial'
   BTserial.print("N:");
   ^~~~~~~~
   Serial
/Users/devinnamaky/Downloads/otto-diy-plus/Codes/OttoPLUS_APP_V10/OttoPLUS_APP_V10.ino: In function 'void requestBattery()':
OttoPLUS_APP_V10:750:3: error: 'BTserial' was not declared in this scope
   BTserial.print("B:");
   ^~~~~~~~
/Users/devinnamaky/Downloads/otto-diy-plus/Codes/OttoPLUS_APP_V10/OttoPLUS_APP_V10.ino:750:3: note: suggested alternative: 'Serial'
   BTserial.print("B:");
   ^~~~~~~~
   Serial
/Users/devinnamaky/Downloads/otto-diy-plus/Codes/OttoPLUS_APP_V10/OttoPLUS_APP_V10.ino: In function 'void requestProgramId()':
OttoPLUS_APP_V10:762:3: error: 'BTserial' was not declared in this scope
   BTserial.print("I:");
   ^~~~~~~~
/Users/devinnamaky/Downloads/otto-diy-plus/Codes/OttoPLUS_APP_V10/OttoPLUS_APP_V10.ino:762:3: note: suggested alternative: 'Serial'
   BTserial.print("I:");
   ^~~~~~~~
   Serial
/Users/devinnamaky/Downloads/otto-diy-plus/Codes/OttoPLUS_APP_V10/OttoPLUS_APP_V10.ino: In function 'bool checkIfConnected()':
OttoPLUS_APP_V10:815:17: error: 'BTserial' was not declared in this scope
           while(BTserial.available() > 0) {
                 ^~~~~~~~
/Users/devinnamaky/Downloads/otto-diy-plus/Codes/OttoPLUS_APP_V10/OttoPLUS_APP_V10.ino:815:17: note: suggested alternative: 'Serial'
           while(BTserial.available() > 0) {
                 ^~~~~~~~
                 Serial
Multiple libraries were found for "Servo.h"
 Used: /Users/devinnamaky/Google Drive/Arduino/libraries/Servo
 Not used: /Applications/Arduino.app/Contents/Java/libraries/Servo
Multiple libraries were found for "Adafruit_NeoPixel.h"
 Used: /Users/devinnamaky/Google Drive/Arduino/libraries/Adafruit_NeoPixel
 Not used: /Users/devinnamaky/Google Drive/Arduino/libraries/OttoDIYLib-master
Multiple libraries were found for "SerialCommand.h"
 Used: /Users/devinnamaky/Google Drive/Arduino/libraries/Arduino-SerialCommand-master
 Not used: /Users/devinnamaky/Google Drive/Arduino/libraries/OttoDIYLib-master
exit status 1
'SoftwareSerial' does not name a type; did you mean 'HardwareSerial'?

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
`

**Comment by cparrapa** [comment]
it looks like you have duplicates of some of the libraries

**Comment by DrNebin** [comment]
I deleted the duplicates and it worked. Thanks.
