### ISSUE TITLE
possible bug

### ISSUE THREAD

**Issue by sentamugo7** [OttoDIY/OttoDIYLib#16]
Otto9.cpp [void Otto9::walk() routine]
line 251 has:
  int O[4] = {0, 0, 4, -4};

Oscillator.h
line 46 has:
    unsigned int _O;  //-- Offset (degrees)

O[4][3] is putting -4 into an unsigned int

**Comment by lfrohman** [comment]
sorry, this is a duplicate of issue
"variable "O" is defined as a 'unsigned int' instead of 'int' #7 by TokenTotem"

**Comment by sentamugo7** [comment]
sorry, this is a duplicate of issue
"variable "O" is defined as a 'unsigned int' instead of 'int' #7 by TokenTotem"

**Comment by cparrapa** [comment]
How to fix this?

**Comment by sentamugo7** [comment]
> 
> 
> How to fix this?

So in Oscillator.h, lines 45-47 are:

    unsigned int _A;  //-- Amplitude (degrees)
    unsigned int _O;  //-- Offset (degrees)
    unsigned int _T;  //-- Period (miliseconds)

to fix this bug, change _O from
    unsigned int _O;  //-- Offset (degrees)
to
    int _O;  //-- Offset (degrees)

but,
maybe all three (_A, _O, _T) should be changed to int. Also, I don't know if the
original author had a reason to use unsigned int instead of int
