### ISSUE TITLE
has no member named armsup,armwave,armsdown

### ISSUE THREAD

**Issue by suwali** [OttoDIY/OttoDIYLib#17]

**Comment by cparrapa** [comment]
solved here https://github.com/OttoDIY/OttoDIYLib/commit/ead5e94091fa8579c0ab4184141c35d85b2d73b2

**Comment by suwali** [comment]
https://drive.google.com/file/d/14Sbxl-St0pwC8zMReGviOFDjGgUPke3s/view?usp=drivesdk
