### ISSUE TITLE
EEPROM values should have checksum or tag

### ISSUE THREAD

**Issue by anjok** [OttoDIY/OttoDIYLib#22]
When I installed a sample sketch onto a new Nano - with otto.init(true), apparently there was garbage in the EEPROM, which resulted in very tense and weird leg positions.

The EEPROM values should have a tag at the start (say, "OTTO") or a checksum or both. If they don't match, the console should log an error and the values should be discarded.

**Comment by cparrapa** [comment]
Hi @anjok 
Sounds like a good idea how can we implement?

**Comment by anjok** [comment]
The easiest way would be to write a known start, say OTTO, then 2 bytes of length, then either a CRC or simply an XOR over the Len data bytes and then the bytes? On read you would check the prefix and the checksum and print an error if they don't match.

**Comment by sfranzyshen** [comment]
this has been added to the devel todo list ...
