### ISSUE TITLE
where is otto9?

### ISSUE THREAD

**Issue by DanielYWoo** [OttoDIY/OttoDIYLib#33]
Sorry, just get back to this after several years, look at my existing code, I was using otto9, but now is it gone?

**Comment by cparrapa** [comment]
Hi @DanielYWoo 
It is in the releases page https://github.com/OttoDIY/OttoDIYLib/releases
But why do you need to use an old version?

**Comment by DanielYWoo** [comment]
@cparrapa I just took my Otto out of a dusty box which was not opened in years ;-)
I can find the commit id and I got the code back. problem solved !
