### ISSUE TITLE
variable "O" is defined as a 'unsigned int' instead of 'int'

### ISSUE THREAD

**Issue by TokenTotem** [OttoDIY/OttoDIYLib#7]
At line 26 and 46 in oscillator.h, variable "O" is defined as a 'unsigned int' instead of 'int'. 
"O" have negative value such as when Otto walk (Otto9.cpp line 254).
There is no apparent impact on Arduino/Atmega but math results are out of wack on ESP32.

Solution: Change data type from "unsigned int" to "int" for variable "O" and "A" at lines 25,26,45,46 in oscillator.h

**Comment by cparrapa** [comment]
Hi Thanks!
Does this work also for ESP8266?

**Comment by TokenTotem** [comment]
Hello, I've not tested with ESP8266 but it should work.

**Comment by cparrapa** [comment]
Hi @TokenTotem @lfrohman @sentamugo7 
Can you do a PR please?

Thanks!

**Comment by sentamugo7** [comment]
please test this pull request before merge. Thanks.

**Comment by cparrapa** [comment]
fixed on https://github.com/OttoDIY/OttoDIYLib/pull/19
