### ISSUE TITLE
Single Code Set: Merge OttoDIYESP & OttoDIYLib 

### ISSUE THREAD

**Issue by sfranzyshen** [OttoDIY/OttoDIYLib#8]
after looking at the differences between these two code sets ... it seems they could be merged into one. Is there interest in doing so? or should we continue developing for both?

**Comment by sfranzyshen** [comment]
thread already in OttoDIYESP

**Comment by cparrapa** [comment]
Yes @sfranzyshen 
Better to work on this in the other repo, this repo for the main Otto DIY Libraries is link to all our documentation so it has to work as it is.
