### ISSUE TITLE
OTTO programs using touch sensor behave oddly

### ISSUE THREAD

**Issue by marttiojanen** [OttoDIY/OttoDIYLib#9]
OTTO touch sensor is using TTP223B chip. Sensor is hardwired to work in "toggle" mode and power on initial state is LOW. At every touch sensor toggles its output between states. Program must first expect to read HIGH value and then LOW value etc.

**Comment by marttiojanen** [comment]
This code replacement works ok in OttoPLUS_touchmodes_v9.ino and should work also in OttoPLUS_touchultrasound_v9.ino
//-- Setup ------------------------------------------------------//
///////////////////////////////////////////////////////////////////
void setup(){
  Otto.init(PIN_YL,PIN_YR,PIN_RL,PIN_RR,true, -1, 13, 8, 9);
  pinMode(sensorPin, INPUT);
  Otto.home();
  Otto.sing(S_happy); // a happy Otto :)
}
// touch sensor is in "toggle mode", initial value is LOW
// program expects HIGH value for first touch
// and then expects LOW value for second touch
// and then again HIGH and LOW etc.
//
  int estado = HIGH; //first expected touch value
  
///////////////////////////////////////////////////////////////////
//-- Principal Loop ---------------------------------------------//
///////////////////////////////////////////////////////////////////
void loop() {
	
   if (digitalRead(sensorPin) == estado)
   {
	   if (estado == HIGH)
	   {
	   estado = LOW;//toggle expect value
	   }
	   else
	   {
	   	estado = HIGH;//toggle expect value
	   }
     Otto.sing(S_buttonPushed);
     movement = movement + 1;
     delay(500);
   }

**Comment by cparrapa** [comment]
Hi @marttiojanen
Thanks it looks great can you do a PR please?

**Comment by marttiojanen** [comment]
A ”PR”? What is that?

By the way, I am testing speech recognition module (hicell) on my otto. Where do I connect the communication leads serial rx/tx?
They are set on the program:

#define SOFTSERIAL_RX_PIN  6
#define SOFTSERIAL_TX_PIN  7

Does that mean that pins 6&7 are defined by sw as rx/tx pins?

Best regards,
Martti

**Comment by cparrapa** [comment]
Hi 
A Pull request follow this guide https://guides.github.com/activities/hello-world/#:~:text=Pull%20Requests%20are%20the%20heart,the%20content%20from%20both%20branches.
